"""
AION OS - Candidate Generator
===============================

Uses the local LLM as an internal optimizer, NOT an autonomous agent.

Instead of letting the model touch the running system:
  1. Generate candidate changes OFFLINE
  2. Ask the LLM to propose:
     - New/refined detection patterns given recent FP/FN
     - Prompt tweaks for more precise/shorter reports
     - New feature combinations for correlation
  3. Return structured CandidateChange objects for simulation

The LLM never writes code or modifies the running system.
It proposes declarative config changes that are validated + tested.
"""

import json
import logging
from datetime import datetime
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Optional, Any
from pathlib import Path
from enum import Enum

logger = logging.getLogger("aionos.improvement.candidate")


# =============================================================================
# DATA MODELS
# =============================================================================

class ChangeType(Enum):
    """Types of changes the candidate generator can propose."""
    THRESHOLD_ADJUSTMENT = "threshold_adjustment"
    PATTERN_WEIGHT = "pattern_weight"
    TRIAGE_RULE = "triage_rule"
    PROMPT_TEMPLATE = "prompt_template"
    NEW_CORRELATION = "new_correlation"
    CATEGORY_MAPPING = "category_mapping"


@dataclass
class CandidateChange:
    """
    A single proposed change generated by the LLM.

    This is a declarative description of what to change,
    not executable code.
    """
    id: str
    change_type: str  # ChangeType value
    target: str       # e.g., "thresholds.mfa_fatigue_threshold"
    description: str  # Human-readable explanation
    reasoning: str    # Why the LLM thinks this helps
    old_value: Any = None
    new_value: Any = None
    confidence: float = 0.0  # LLM's confidence (0-1)
    evidence: List[str] = field(default_factory=list)  # Alert IDs, FP/FN refs
    created_at: str = ""
    status: str = "proposed"  # "proposed", "tested", "approved", "rejected"

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.utcnow().isoformat()

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict) -> "CandidateChange":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class CandidateProposal:
    """
    A complete improvement proposal (may contain multiple changes).
    """
    id: str
    description: str
    changes: List[CandidateChange] = field(default_factory=list)
    metrics_context: Dict[str, Any] = field(default_factory=dict)
    created_at: str = ""
    status: str = "proposed"  # "proposed", "shadow_testing", "approved", "rejected"
    target_policy_version: Optional[int] = None

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.utcnow().isoformat()

    def to_dict(self) -> dict:
        return asdict(self)


# =============================================================================
# CANDIDATE GENERATOR
# =============================================================================

# System prompt for the LLM optimizer role
OPTIMIZER_SYSTEM_PROMPT = """\
You are AION OS's internal detection optimizer. Your role is to propose 
DECLARATIVE configuration changes that improve detection quality.

You are NOT an autonomous agent. You CANNOT modify code.
You can ONLY propose changes to:
  - Detection thresholds (numeric values)
  - Pattern weights (enable/disable, priority)
  - Triage rules (when to escalate, auto-close, etc.)
  - LLM prompt templates (for better reports)
  - New correlation combinations (e.g., "badge + USB + VPN")
  - Category mappings

You MUST NOT propose changes to:
  - Authentication or authorization logic
  - Input validation or sanitization
  - Memory limits or resource bounds
  - Audit logging or compliance controls
  - Core security invariants

For each proposed change, provide:
  1. What to change (target parameter path)
  2. Current value and proposed new value
  3. Why this improves detection (reasoning)
  4. Evidence from the metrics/feedback data
  5. Your confidence level (0-1)

Respond in valid JSON matching the CandidateChange schema."""


class CandidateGenerator:
    """
    Generates candidate detection improvements using LLM analysis.

    Uses the LLM as a reasoning engine to:
      - Analyze false positive patterns
      - Identify missed detection opportunities
      - Propose threshold adjustments
      - Suggest new correlation rules
      - Improve prompt templates

    All proposals are structured data — never raw code.
    """

    # Directories for storing proposals
    PROPOSALS_DIR = Path(__file__).parent.parent / "knowledge" / "improvement" / "proposals"

    def __init__(self, llm_provider: str = "local"):
        """
        Args:
            llm_provider: Which LLM to use for generation.
                "local" = Ollama/LMStudio (default, private)
                "claude" = Claude API
                "mock" = Return canned proposals (testing)
        """
        self.llm_provider = llm_provider
        self.PROPOSALS_DIR.mkdir(parents=True, exist_ok=True)

    def generate_from_metrics(
        self,
        metrics: Dict[str, Any],
        recent_fps: List[Dict[str, Any]],
        recent_fns: List[Dict[str, Any]],
        current_policy: Dict[str, Any],
    ) -> CandidateProposal:
        """
        Generate improvement candidates based on current metrics and feedback.

        Args:
            metrics: Current DetectionMetrics as dict.
            recent_fps: Recent false positive alert outcomes.
            recent_fns: Recent false negative (missed) outcomes.
            current_policy: Current active policy as dict.

        Returns:
            CandidateProposal with suggested changes.
        """
        prompt = self._build_analysis_prompt(
            metrics, recent_fps, recent_fns, current_policy
        )

        if self.llm_provider == "mock":
            changes = self._mock_generate(metrics, recent_fps, recent_fns)
        else:
            changes = self._llm_generate(prompt)

        proposal = CandidateProposal(
            id=f"proposal_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
            description=self._summarize_proposal(changes),
            changes=changes,
            metrics_context=metrics,
        )

        self._save_proposal(proposal)
        logger.info(
            f"Generated proposal {proposal.id} with {len(changes)} changes"
        )
        return proposal

    def generate_prompt_refinement(
        self,
        template_name: str,
        current_template: str,
        sample_outputs: List[str],
        feedback: List[str],
    ) -> CandidateChange:
        """
        Generate a refined LLM prompt template based on output feedback.

        Args:
            template_name: Name of the prompt template to refine.
            current_template: Current template text.
            sample_outputs: Example outputs from the current template.
            feedback: Analyst feedback on those outputs.

        Returns:
            CandidateChange with the refined template.
        """
        prompt = (
            f"Refine this prompt template for better output quality.\n\n"
            f"Template name: {template_name}\n"
            f"Current template:\n{current_template}\n\n"
            f"Sample outputs:\n" + "\n---\n".join(sample_outputs[:3]) + "\n\n"
            f"Analyst feedback:\n" + "\n".join(feedback[:5]) + "\n\n"
            f"Provide an improved template that addresses the feedback. "
            f"Keep the same {{variable}} placeholders."
        )

        if self.llm_provider == "mock":
            new_template = current_template + "\n\n[REFINED: Added structure]"
        else:
            new_template = self._llm_generate_text(prompt)

        return CandidateChange(
            id=f"prompt_{template_name}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
            change_type=ChangeType.PROMPT_TEMPLATE.value,
            target=f"prompt_templates.{template_name}",
            description=f"Refined prompt template '{template_name}'",
            reasoning="Analyst feedback indicated output quality issues",
            old_value=current_template,
            new_value=new_template,
            confidence=0.6,
            evidence=[f"feedback: {f}" for f in feedback[:3]],
        )

    def generate_new_correlation(
        self,
        mis_detections: List[Dict[str, Any]],
        existing_patterns: List[str],
    ) -> CandidateChange:
        """
        Propose a new event correlation combination based on mis-detections.

        E.g., "badge + USB + VPN after hours" that the system currently
        doesn't correlate but should.

        Args:
            mis_detections: Recent mis-categorized or missed alerts.
            existing_patterns: Names of currently active patterns.

        Returns:
            CandidateChange proposing a new correlation pattern.
        """
        prompt = (
            f"Analyze these mis-detections and propose a new correlation rule.\n\n"
            f"Mis-detections:\n{json.dumps(mis_detections[:10], indent=2)}\n\n"
            f"Currently active patterns:\n{json.dumps(existing_patterns, indent=2)}\n\n"
            f"Propose a new multi-event correlation that would have caught "
            f"these. Include: pattern name, event sequence, time window, "
            f"and minimum stages to alert."
        )

        if self.llm_provider == "mock":
            return CandidateChange(
                id=f"corr_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
                change_type=ChangeType.NEW_CORRELATION.value,
                target="pattern_weights",
                description="New correlation: badge_usb_vpn_afterhours",
                reasoning="Missed 3 insider threats that combined physical badge + USB + VPN",
                new_value={
                    "name": "badge_usb_vpn_afterhours",
                    "stages": ["badge_access", "usb_activity", "vpn_access"],
                    "time_window_days": 1,
                    "severity": "P1",
                    "min_stages_to_alert": 3,
                },
                confidence=0.7,
                evidence=[m.get("alert_id", "") for m in mis_detections[:5]],
            )
        else:
            return self._llm_generate_correlation(prompt)

    # -------------------------------------------------------------------------
    # LLM interaction (pluggable backends)
    # -------------------------------------------------------------------------

    def _build_analysis_prompt(
        self,
        metrics: Dict[str, Any],
        fps: List[Dict[str, Any]],
        fns: List[Dict[str, Any]],
        policy: Dict[str, Any],
    ) -> str:
        """Build the analysis prompt for the LLM."""
        return (
            f"{OPTIMIZER_SYSTEM_PROMPT}\n\n"
            f"---\n"
            f"CURRENT METRICS:\n{json.dumps(metrics, indent=2)}\n\n"
            f"RECENT FALSE POSITIVES ({len(fps)}):\n"
            f"{json.dumps(fps[:10], indent=2, default=str)}\n\n"
            f"RECENT MISSED THREATS ({len(fns)}):\n"
            f"{json.dumps(fns[:10], indent=2, default=str)}\n\n"
            f"CURRENT POLICY (thresholds):\n"
            f"{json.dumps(policy.get('thresholds', {}), indent=2)}\n\n"
            f"Propose 1-5 specific changes to improve detection quality.\n"
            f"Return a JSON array of CandidateChange objects."
        )

    def _llm_generate(self, prompt: str) -> List[CandidateChange]:
        """Call the LLM and parse structured changes."""
        try:
            if self.llm_provider == "claude":
                raw = self._call_claude(prompt)
            elif self.llm_provider in ("ollama", "lmstudio", "local"):
                raw = self._call_local(prompt)
            else:
                return self._mock_generate({}, [], [])

            # Parse JSON from LLM response
            changes = self._parse_llm_response(raw)
            return changes

        except Exception as e:
            logger.error(f"LLM generation failed: {e}")
            return []

    def _llm_generate_text(self, prompt: str) -> str:
        """Call the LLM and return raw text."""
        try:
            if self.llm_provider == "claude":
                return self._call_claude(prompt)
            elif self.llm_provider in ("ollama", "lmstudio", "local"):
                return self._call_local(prompt)
            return ""
        except Exception as e:
            logger.error(f"LLM text generation failed: {e}")
            return ""

    def _llm_generate_correlation(self, prompt: str) -> CandidateChange:
        """Call the LLM to propose a correlation pattern."""
        raw = self._llm_generate_text(prompt)
        try:
            data = json.loads(raw)
            return CandidateChange.from_dict(data)
        except Exception:
            return CandidateChange(
                id=f"corr_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}",
                change_type=ChangeType.NEW_CORRELATION.value,
                target="pattern_weights",
                description="Failed to parse LLM correlation proposal",
                reasoning=raw[:500] if raw else "LLM returned no response",
                confidence=0.0,
            )

    def _call_claude(self, prompt: str) -> str:
        """Call Claude API (lazy import to avoid dependency issues)."""
        try:
            import anthropic
            import os
            client = anthropic.Anthropic(
                api_key=os.environ.get("ANTHROPIC_API_KEY", "")
            )
            response = client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=4096,
                temperature=0.2,
                messages=[{"role": "user", "content": prompt}],
            )
            return response.content[0].text
        except Exception as e:
            logger.error(f"Claude API call failed: {e}")
            return ""

    def _call_local(self, prompt: str) -> str:
        """Call local LLM via Ollama or LM Studio."""
        try:
            import httpx
            import os

            # Try LM Studio first, then Ollama
            lmstudio_url = os.environ.get(
                "LMSTUDIO_URL", "http://localhost:1234/v1/chat/completions"
            )
            ollama_url = os.environ.get(
                "OLLAMA_URL", "http://localhost:11434/api/generate"
            )

            # Try LM Studio (OpenAI-compatible)
            try:
                resp = httpx.post(
                    lmstudio_url,
                    json={
                        "messages": [{"role": "user", "content": prompt}],
                        "temperature": 0.2,
                        "max_tokens": 4096,
                    },
                    timeout=120,
                )
                if resp.status_code == 200:
                    return resp.json()["choices"][0]["message"]["content"]
            except Exception:
                pass

            # Fallback to Ollama
            resp = httpx.post(
                ollama_url,
                json={
                    "model": os.environ.get("OLLAMA_MODEL", "llama3.1"),
                    "prompt": prompt,
                    "stream": False,
                },
                timeout=120,
            )
            if resp.status_code == 200:
                return resp.json().get("response", "")

        except Exception as e:
            logger.error(f"Local LLM call failed: {e}")
        return ""

    def _parse_llm_response(self, raw: str) -> List[CandidateChange]:
        """Parse LLM response into CandidateChange objects."""
        if not raw:
            return []

        # Try to extract JSON from the response
        try:
            # Find JSON array in response
            start = raw.find("[")
            end = raw.rfind("]") + 1
            if start >= 0 and end > start:
                data = json.loads(raw[start:end])
                return [CandidateChange.from_dict(d) for d in data]

            # Try single object
            start = raw.find("{")
            end = raw.rfind("}") + 1
            if start >= 0 and end > start:
                data = json.loads(raw[start:end])
                return [CandidateChange.from_dict(data)]

        except json.JSONDecodeError:
            logger.warning("Failed to parse LLM JSON response")

        return []

    def _mock_generate(
        self,
        metrics: Dict[str, Any],
        fps: List[Dict[str, Any]],
        fns: List[Dict[str, Any]],
    ) -> List[CandidateChange]:
        """Generate mock candidates for testing."""
        changes = []

        # If high false positive rate, propose threshold increase
        fp_rate = metrics.get("noise_ratio", 0)
        if fp_rate > 0.3:
            changes.append(CandidateChange(
                id="mock_reduce_noise_1",
                change_type=ChangeType.THRESHOLD_ADJUSTMENT.value,
                target="thresholds.baseline_confidence_threshold",
                description="Raise confidence threshold to reduce noise",
                reasoning=f"Current noise ratio is {fp_rate:.0%}, too high",
                old_value=0.5,
                new_value=0.6,
                confidence=0.75,
                evidence=[fp.get("alert_id", "") for fp in fps[:3]],
            ))

        # Always propose at least one change for testing
        if not changes:
            changes.append(CandidateChange(
                id="mock_default_1",
                change_type=ChangeType.THRESHOLD_ADJUSTMENT.value,
                target="thresholds.mfa_fatigue_threshold",
                description="Adjust MFA fatigue threshold from 3 to 5",
                reasoning="Recent feedback suggests 3 is too sensitive for environments with frequent MFA",
                old_value=3,
                new_value=5,
                confidence=0.65,
            ))

        return changes

    # -------------------------------------------------------------------------
    # Helpers
    # -------------------------------------------------------------------------

    def _summarize_proposal(self, changes: List[CandidateChange]) -> str:
        """Create a human-readable summary of proposed changes."""
        if not changes:
            return "No changes proposed"

        parts = [f"{len(changes)} proposed change(s):"]
        for c in changes:
            parts.append(f"  - {c.description} ({c.change_type})")
        return "\n".join(parts)

    def _save_proposal(self, proposal: CandidateProposal):
        """Persist proposal to disk."""
        path = self.PROPOSALS_DIR / f"{proposal.id}.json"
        with open(path, "w") as f:
            json.dump(proposal.to_dict(), f, indent=2, default=str)
